### PR TITLE
change product to hardcoded number fixes #1012 fixes #998 fixes #997

### LINKED ISSUE #998: xtb compialtion failure ...
### Discussed in https://github.com/grimme-lab/xtb/discussions/997

<div type='discussions-op-text'>

<sup>Originally posted by **husakm** March 20, 2024</sup>
I was trying to recompile xtb (by gfortran 10). All worked OK until aprox. 58% ready, thani have got following:

```
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4039:
45:

 4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4041:
44:

 4041 |   real(wp), intent(in) :: gTrans(3, product(2*ewaldCutR+1)-1)
      |                                            1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4041:
44:

 4041 |   real(wp), intent(in) :: gTrans(3, product(2*ewaldCutR+1)-1)
      |                                            1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4039:
45:

 4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4039:
45:

 4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: 'array' argument of 'product' intrinsic at (1) must be an array
/cygdrive/m/My_Project/Fortran/XTB_cygwin/xtb-6.7.0/src/gfnff/gfnff_eg.f90:1064:
68:

 1064 |            write(*,'(10x,"No H-atom found in this bond ",i0,1x,i0)'), ia
t,jat
```
Any idea what is wrong ?

Michal</div>

### LINKED ISSUE #1012: xtb-6.7.0/src/gfnff/gfnff_eg.f90 compilation error
I get the following error during compilation of xtb-6.7.0 on Linux (Clear Linux)

uname -a `Linux samara 6.0.7-1207.native #1 SMP Thu Nov 3 09:15:51 PDT 2022 x86_64 GNU/Linux`

GCC version `12.2.1`

```4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: ‘array’ argument of ‘product’ intrinsic at (1) must be an array
/home/lsd/Downloads/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4041:44:

 4041 |   real(wp), intent(in) :: gTrans(3, product(2*ewaldCutR+1)-1)
      |                                            1
Error: ‘array’ argument of ‘product’ intrinsic at (1) must be an array
/home/lsd/Downloads/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4041:44:

 4041 |   real(wp), intent(in) :: gTrans(3, product(2*ewaldCutR+1)-1)
      |                                            1
Error: ‘array’ argument of ‘product’ intrinsic at (1) must be an array
/home/lsd/Downloads/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4039:45:

 4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: ‘array’ argument of ‘product’ intrinsic at (1) must be an array
/home/lsd/Downloads/xtb-6.7.0/src/gfnff/gfnff_eg.f90:4039:45:

 4039 |   real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
      |                                             1
Error: ‘array’ argument of ‘product’ intrinsic at (1) must be an array
/home/lsd/Downloads/xtb-6.7.0/src/gfnff/gfnff_eg.f90:2023:12:```

### PR DESCRIPTION
**Pull request by james-qbraid**
I had the same compilation error as reference in #1012 , #998,  and #997.

This is clearly some sort of bug in gcc as it is clearly passing an array to product.

Unless I am misunderstanding something, changing to hardcoded numbers should not pose a problem. If desired, I could also do the explicit product. e.g. `(2*ewaldCutD(1) + 1)*(2*ewaldCutD(2) + 1)*(2*ewaldCutD(3) + 1)`

Closes #1012
Closes #998
Closes #997

### CODE REVIEW

File: src/gfnff/gfnff_eg.f90 [hunk 1]
```diff
@@ -4039,9 +4039,9 @@ function get_cf(rTrans,gTrans,vol,avgAlp) result(cf)
   integer, parameter :: ewaldCutD(3) = 2
   integer, parameter :: ewaldCutR(3) = 2
   ! real space lattice vectors
-  real(wp), intent(in) :: rTrans( 3, product(2*ewaldCutD+1))
+  real(wp), intent(in) :: rTrans(3, 125)  !previously rTrans(3, product(2*ewaldCutD + 1))
```
Comment (awvwgk) [inline src/gfnff/gfnff_eg.f90:4042]:
```suggestion
  real(wp), intent(in) :: rTrans(:, :)
```

File: src/gfnff/gfnff_eg.f90 [hunk 2]
```diff
@@ -4039,9 +4039,9 @@ function get_cf(rTrans,gTrans,vol,avgAlp) result(cf)
...
   ! reciprocal space lattice vectors
-  real(wp), intent(in) :: gTrans(3, product(2*ewaldCutR+1)-1)
+  real(wp), intent(in) :: gTrans(3, 124)  !previously gTrans(3, product(2*ewaldCutR + 1) - 1)
```
Comment (awvwgk) [inline src/gfnff/gfnff_eg.f90:4044]:
```suggestion
  real(wp), intent(in) :: gTrans(:, :)
```

**Review by awvwgk — CHANGES_REQUESTED** [review]
If these arrays were allocated with the right dimensions there is no need at all to specify the shape.

**Comment by james-qbraid** [comment]
> If these arrays were allocated with the right dimensions there is no need at all to specify the shape.

I agree. Didn't know if you wanted them explicitly defined for some reason.

**Review by awvwgk — APPROVED** [review]
Thanks for sharing. Looks good to me now.
